# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /news/:year/:month/:day/:title/index.html

include: ["atom.xml"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "bin", "vendor", "Gemfile", "Gemfile.lock", "build", "publish-production", "publish-staging"]
markdown: kramdown
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : AeroGear

production_url : http://aerogear.org

navigation:
- desc: Get The Gear
  url: /download
- desc: Community
  url: /community
- desc: Documentation
  url: /docs
- desc: Road Map
  url: "/docs/planning"
- desc: Sources
  url: "http://github.com/aerogear"
#- desc: Examples / Demos
#  url: "#"

