# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title.html

include: ["atom.xml"]
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "bin", "vendor", "Gemfile", "Gemfile.lock", "build"]
markdown: kramdown
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : AeroGear

production_url : http://aerogear.org

navigation:
- desc: Get The Gear
  url: /
- desc: Community
  url: /community
- desc: Documentation
  url: /docs
- desc: Road Map
  url: "#"
- desc: Examples / Demos
  url: "#"
- desc: Source
  url: "http://github.com/aerogear"

